# Generated by Django 4.1.4 on 2023-02-03 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small (Up to 30 lbs)'), ('M', 'Medium (30 - 50 lbs)'), ('L', 'Large (50 lbs and Up)')], default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True)),
                ('breed', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='booking.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('time', models.IntegerField(choices=[(10, '10:00 AM'), (13, '1:00 PM'), (15, '3:00 PM')])),
                ('service', models.CharField(choices=[('E', 'Express Grooming'), ('F', 'Full Dog Grooming'), ('P', 'Spa Premium Grooming')], default='E', max_length=20)),
                ('add_ons', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'None'), (1, 'Tooth Brushing'), (2, 'De-matting'), (3, 'Blueberry Facial'), (4, 'Body massage'), (5, 'Hydro massage bath'), (6, 'Oatmeal or Aloe Conditioning')], default=0, max_length=6)),
                ('booked', models.BooleanField(default=False)),
                ('dog', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.owner')),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
