# Generated by Django 4.1.4 on 2023-02-07 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_pet_date_of_birth_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[(10, '10:00 AM'), (13, '1:00 PM'), (15, '3:00 PM')]),
        ),
    ]
