# Generated by Django 4.1.4 on 2023-02-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_created_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.IntegerField(choices=[(10, '10:00 AM'), (13, '1:00 PM'), (15, '3:00 PM')]),
        ),
    ]
